version: "3"
services:
  flask_server:
    container_name: flask_server
    restart: always
    build:
      context: ./flask_server
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=dev
      - FLASK_APP=app
      - FLASK_RUN_HOST=0.0.0.0
      # - FLASK_DEBUG=ON
    ports:
      - 5000:5000
    volumes:
      - ./flask_server:/flask_server/
    depends_on:
      - tensorflow-serving
    networks:
      ml-network:
        aliases:
          - flask_server

  tensorflow-serving:
    image: tensorflow/serving
    container_name: tensorflow-serving
    ports:
      - 8500:8500
      - 8501:8501
    volumes:
      - ./serving/conf:/tensorflow-serving/conf/
      - ./serving/model-data:/tensorflow-serving/models/
    command:
      - "--model_config_file=/tensorflow-serving/conf/tensorflow-serving.conf"
      - "--model_config_file_poll_wait_seconds=60"
    networks:
      - ml-network

volumes:
  ml-db:
    name: ml-db
  tensorflow-serving_data:
    driver: local

networks:
  ml-network: