version: "3"
services:
  plateducate-be-server:
    container_name: plateducate-be-server
    build:
      context: ./plateducate-be
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app
      - PYTHONUNBUFFERED=1
    ports:
      - 4000:4000
    volumes:
      - ./plateducate-be/app/.env:/plateducate-be/app/.env
      - ./plateducate-be/app/__init__.py:/plateducate-be/app/__init__.py
      - ./plateducate-be/app/auth.py:/plateducate-be/app/auth.py
      - ./plateducate-be/app/food.py:/plateducate-be/app/food.py
      - ./plateducate-be/app/nutrients.py:/plateducate-be/app/nutrients.py
      - ./plateducate-be/app/objectDetection.py:/plateducate-be/app/objectDetection.py
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - plateducate-ml_ml-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  plateducate-ml_ml-network:
    external: true
